backend:
  name: git-gateway
  branch: stripe-site
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
  - name: "seo"
    label: "SEO"
    files:
      - file: "src/SEO/SeoFromCms.json"
        label: "SEO Tags"
        name: "SEO"
        fields:
          - {label: "Title", name: "title", widget: string}
          - {label: "Description", name: "description", widget: string}
          - {label: "Author", name: "author", widget: string}
          - {label: "URL", name: "url", widget: string}
          - {label: "Keywords", name: "keywords", widget: "list"}
  - name: "theme"
    label: "Theme"
    files:
      - file: "src/theme/theme.json"
        label: "Theme"
        name: "theme"
        fields:
          - {label: "Primary Color", name: "primaryColor", widget: color}
          - {label: "Secondary Color", name: "secondaryColor", widget: color}
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/content/home.json"
        label: "Home Page"
        name: "Home"
        fields:
          - label: "IntroCard"
            name: "introCard" 
            widget: "object" 
            fields: 
              - label: "Title"
                name: "title"
                widget: "string"
              - label: "Description"
                name: "description"
                widget: "string"
              - label: "Buttons"
                name: "buttons"
                widget: "object"
                fields: 
                  - label: "Button Text 1"
                    name: "buttonText1"
                    widget: "string" 
                  - label: "Button Text 2"
                    name: "buttonText2"
                    widget: "string"
                  - label: "Button Text 3"
                    name: "buttonText3" 
                    widget: "string"
          - label: "Features"
            name: "features"
            widget: "object"
            fields:
              - label: "Title"
                name: "title"
                widget: "string"
              - label: "Description"
                name: "description"
                widget: "string"
              - label: "Items"
                name: "items"
                widget: "list"
                max: 3
                min: 3
                fields:
                  - label: "Title"
                    name: "title"
                    widget: "string"
                  - label: "Description"
                    name: "description"
                    widget: "string"
                  - label: "Image"
                    name: "image"
                    widget: "image"
                    allow_multiple: false
          - label: "Menu"
            name: "menu"
            widget: "object"
            fields:
              - label: "Title"
                name: "title"
                widget: "string"
              - label: "Description"
                name: "description"
                widget: "string"
              - label: "Items"
                name: "items"
                widget: "list"
                max: 3
                min: 3
                fields:
                  - label: "Title"
                    name: "title"
                    widget: "string"
                  - label: "Description"
                    name: "description"
                    widget: "string"
          - label: "Product Info"
            name: "productInfo"
            widget: "list"
            max: 2
            min: 2
            fields:
              - label: "Title"
                name: "title"
                widget: "string"
              - label: "Description"
                name: "description"
                widget: "string"
              - label: "Button Text"
                name: "buttonText"
                widget: "string"
          - label: "Banner"
            name: "banner"
            widget: "object"
            fields: 
              - label: "Title" 
                name: "title" 
                widget: "string"
              - label: "Description" 
                name: "description"
                widget: "string"
              - label: "Button Text" 
                name: "buttonText"
                widget: "string" 
      - file: "src/pages/content/pricing.json"
        label: "Pricing Page"
        name: "pricing"
        fields:
          - label: "Title"
            name: "title"
            widget: "string"
          - label: "Description"
            name: "description"
            widget: "string"
          - label: "Plans"
            name: "plans"
            widget: "list"
            min: 3
            max: 3
            fields:
              - label: "Plan Name"
                name: "planName"
                widget: "string"
              - label: "Price"
                name: "price"
                widget: "string"
              - label: "Cycle"
                name: "cycle"
                widget: "string"
              - label: "Description"
                name: "description"
                widget: "string"
              - label: "Featured"
                name: "isFeatured"
                widget: "boolean"
              - label: "Perks"
                name: "perks"
                widget: "list"
                min: 5
                max: 5
                field: {label: "Perk", name: "perk", widget: "string"}
      - file: "src/pages/content/how-it-works.json"
        label: "How it works Page"
        name: "how-it-works"
        fields:
          - label: "Cards"
            name: "cards"
            widget: "list"
            fields:
              - label: "Title"
                name: "title"
                widget: "string"
              - label: "Description"
                name: "description"
                widget: "string"
        