backend:
  name: github
  repo: santhoshivan23/gatsby-business-starter
  branch: stripe-site
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
  - name: "seo"
    label: "SEO"
    files:
      - file: "src/SEO/SeoFromCms.json"
        label: "SEO Tags"
        name: "SEO"
        fields:
          - {label: "Title", name: "title", widget: string}
          - {label: "Description", name: "description", widget: string}
          - {label: "Author", name: "author", widget: string}
          - {label: "URL", name: "url", widget: string}
          - {label: "Keywords", name: "keywords", widget: "list"}
  - name: "theme"
    label: "Theme"
    files:
      - file: "src/theme/theme.json"
        label: "Theme"
        name: "theme"
        fields:
          - {label: "Primary Color", name: "primaryColor", widget: color}
          - {label: "Secondary Color", name: "secondaryColor", widget: color}
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/content/content.json"
        label: "Home Page"
        name: "Home"
        fields:
          - {minimize_collapsed: true, label: "Template Key", name: "templateKey", widget: "hidden", default: "home-page"}
          - {minimize_collapsed: true, label: IntroCard, name: introCard, widget: object, fields: [{label: Title, name: title, widget: string}, {label: Description, name: description, widget: string}, {label: Buttons, name: buttons, widget: object, fields : [{label: Button Text 1, name: buttonText1, widget: string}, {label: Button Text 2, name: buttonText2, widget: string}, {label: Button Text 3, name: buttonText3, widget: string}]}]}
          - label: "Feature Items"
            name: "featureItems"
            minimize_collapsed: true
            widget: "list"
            min: 3
            max: 3
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Description, name: description, widget: string }
          - {
              label: Menu, 
              name: menu,
              widget: object, 
              fields: [
                {label: Title, name: title, widget: string}, 
                {label: Description, name: description, widget: string}, 
                {label: Menu Items, name: menuItems, widget: object, 
                      fields: [
                        {
                          label: Menu Item 1,
                          name: item1,
                          widget: object,
                          fields : [
                          {label: Title, name: title, widget: string}, 
                          {label: Description, name: description, widget: string}, 
                          {label: Image Path, name: imagePath, widget: string}
                        ]
                        },
                        {
                          label: Menu Item 2,
                          name: item2,
                          widget: object,
                          fields : [
                          {label: Title, name: title, widget: string}, 
                          {label: Description, name: description, widget: string}, 
                          {label: Image Path, name: imagePath, widget: string}
                        ]
                        },  
                        {
                          label: Menu Item 3,
                          name: item3,
                          widget: object,
                          fields : [
                          {label: Title, name: title, widget: string}, 
                          {label: Description, name: description, widget: string}, 
                          {label: Image Path, name: imagePath, widget: string}
                        ]
                        },                                          
                  ]
                }
              ]
            }
          - {
            label: Product Info,
            name: productInfo,
            widget: object,
            fields : [
            {  
              label: Product Info 1,
              name: productInfo1,
              widget: object,
              fields: [
                { label: Title, name: title, widget: string },
                { label: Description, name: description, widget: string },
                { label: Image Path, name: imagePath, widget: string },
                { label: Button Text, name: buttonText, widget: string}
              ]
            },
            {  
              label: Product Info 2,
              name: productInfo2,
              widget: object,
              fields: [
                { label: Title, name: title, widget: string },
                { label: Description, name: description, widget: string },
                { label: Image Path, name: imagePath, widget: string },
                { label: Button Text, name: buttonText, widget: string}
              ]
            },
            ]
          }
          - {
            label: "Banner",
            name: "banner",
            widget: "object",
            fields: [
              { label: Title, name: title, widget: string },
              { label: Description, name: description, widget: string},
              { label: Button Text, name: buttonText, widget: string },
            ]
          }